import = [
    "~/.config/alacritty/themes/kanagawa-wave.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 0.97

decorations = "Buttonless"

[font]
normal.family = "Hack nerd font mono"

#regular
size = 9
