import = [
    "~/.config/alacritty/themes/kanagawa-wave.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 6
padding.y = 6

opacity = 0.98

decorations = "Buttonless"

[font]
normal.family = "Hack nerd font mono"

# regular
size = 8.0
